# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
zodiac = Category.create(title: "Zodiac")
celests = Category.create(title: "Solar System")
moon_phases = Category.create(title: "Moon Phases")
seasons = Category.create(title: "Seasons")
full_moons = Category.create(title: "Full Moons")
days = Category.create(title: "Days")
ogham = Category.create(title: "Ogham")
runes = Category.create(title: "Runes")
elements = Category.create(title: "Elements")
directions = Category.create(title: "Directions")
colors = Category.create(title: "Colors")
chakras = Category.create(title: "Chakras")
plants = Category.create(title: "Misc. Plants")
trees = Category.create(title: "Trees")
herbs = Category.create(title: "Herb & Garden")
minerals = Category.create(title: "Gemstones & Minerals")
sea = Category.create(title: "From the Sea")
goddesses = Category.create(title: "Goddesses")
gods = Category.create(title: "Gods")
animals = Category.create(title: "Animals")
marine_life = Category.create(title: "Marine Life")
reptiles = Category.create(title: "Reptiles")
birds = Category.create(title: "Birds")
critters = Category.create(title: "Insect & Misc.")
mythical = Category.create(title: "Magical")
time_of_day = Category.create(title: "Time of Day")
tarot = Category.create(title: "Tarot")
numbers = Category.create(title: "Numbers")
celebrations = Category.create(title: "Celebrations")

Correspondence.create(name: "Virgo", category_id: 1)
Correspondence.create(name: "Jupiter", category_id: 2)
Correspondence.create(name: "Full", category_id: 3)
Correspondence.create(name: "Waxing", category_id: 3)
Correspondence.create(name: "August", category_id: 5)
Correspondence.create(name: "June", category_id: 5)
Correspondence.create(name: "Autumn", category_id: 4)
Correspondence.create(name: "Thursday", category_id: 6)
Correspondence.create(name: "Ruis", category_id: 7)
Correspondence.create(name: "Feoh", category_id: 8)
Correspondence.create(name: "Earth", category_id: 9)
Correspondence.create(name: "North", category_id: 10)
Correspondence.create(name: "Gold", category_id: 11)
Correspondence.create(name: "Orange", category_id: 11)
Correspondence.create(name: "Green", category_id: 11)
Correspondence.create(name: "Sacral", category_id: 12)
Correspondence.create(name: "8", category_id: 28)
Correspondence.create(name: "Grain", category_id: 13)
Correspondence.create(name: "Myrrh", category_id: 13)
Correspondence.create(name: "Elder", category_id: 14)
Correspondence.create(name: "Chestnut", category_id: 14)
Correspondence.create(name: "Maple", category_id: 14)
Correspondence.create(name: "Olive", category_id: 14)
Correspondence.create(name: "Palm", category_id: 14)
Correspondence.create(name: "Mesquite", category_id: 14)
Correspondence.create(name: "Pine", category_id: 14)
Correspondence.create(name: "Oak", category_id: 14)
Correspondence.create(name: "Sycamore", category_id: 14)
Correspondence.create(name: "Bluebell", category_id: 15)
Correspondence.create(name: "Honeysuckle", category_id: 15)
Correspondence.create(name: "Grape", category_id: 15)
Correspondence.create(name: "Agate", category_id: 16)
Correspondence.create(name: "Apatite", category_id: 16)
Correspondence.create(name: "Bloodstone", category_id: 16)
Correspondence.create(name: "Chrysoberyl", category_id: 16)
Correspondence.create(name: "Aventurine", category_id: 16)
Correspondence.create(name: "Citrine", category_id: 16)
Correspondence.create(name: "Chrysoprase", category_id: 16)
Correspondence.create(name: "Dioptase", category_id: 16)
Correspondence.create(name: "Malachite", category_id: 16)
Correspondence.create(name: "Jade", category_id: 16)
Correspondence.create(name: "Moss Agate", category_id: 16)
Correspondence.create(name: "Peridot", category_id: 16)
Correspondence.create(name: "Rhodochrosite", category_id: 16)
Correspondence.create(name: "Salt", category_id: 16)
Correspondence.create(name: "Quartz", category_id: 16)
Correspondence.create(name: "Smoky Quartz", category_id: 16)
Correspondence.create(name: "Topaz", category_id: 16)
Correspondence.create(name: "Tourmaline", category_id: 16)
Correspondence.create(name: "Tiger’s Eye", category_id: 16)
Correspondence.create(name: "Zircon", category_id: 16)
Correspondence.create(name: "Clam", category_id: 17)
Correspondence.create(name: "Abalone", category_id: 17)
Correspondence.create(name: "Cowry", category_id: 17)
Correspondence.create(name: "Mussel", category_id: 17)
Correspondence.create(name: "Oyster", category_id: 17)
Correspondence.create(name: "Cerridwen", category_id: 18)
Correspondence.create(name: "Artio", category_id: 18)
Correspondence.create(name: "Ceres", category_id: 18)
Correspondence.create(name: "Aine", category_id: 18)
Correspondence.create(name: "Astarte", category_id: 18)
Correspondence.create(name: "Danu", category_id: 18)
Correspondence.create(name: "Coventina", category_id: 18)
Correspondence.create(name: "Bast", category_id: 18)
Correspondence.create(name: "Demeter", category_id: 18)
Correspondence.create(name: "Epona", category_id: 18)
Correspondence.create(name: "Fortuna", category_id: 18)
Correspondence.create(name: "Frigg", category_id: 18)
Correspondence.create(name: "Ganga", category_id: 18)
Correspondence.create(name: "Gaia", category_id: 18)
Correspondence.create(name: "Hestia", category_id: 18)
Correspondence.create(name: "Holle", category_id: 18)
Correspondence.create(name: "Inanna", category_id: 18)
Correspondence.create(name: "Isis", category_id: 18)
Correspondence.create(name: "Maia", category_id: 18)
Correspondence.create(name: "Lakshmi", category_id: 18)
Correspondence.create(name: "Rhea", category_id: 18)
Correspondence.create(name: "Rhiannon", category_id: 18)
Correspondence.create(name: "Sedna", category_id: 18)
Correspondence.create(name: "Cernunnos", category_id: 19)
Correspondence.create(name: "Jupiter", category_id: 19)
Correspondence.create(name: "the Dagda", category_id: 19)
Correspondence.create(name: "the Green Man", category_id: 19)
Correspondence.create(name: "Enki", category_id: 19)
Correspondence.create(name: "Hades", category_id: 19)
Correspondence.create(name: "Pushan", category_id: 19)
Correspondence.create(name: "Saturn", category_id: 19)
Correspondence.create(name: "Zeus", category_id: 19)
Correspondence.create(name: "Vertimnus", category_id: 19)
Correspondence.create(name: "Cow", category_id: 20)
Correspondence.create(name: "Buffalo", category_id: 20)
Correspondence.create(name: "Ox", category_id: 20)
Correspondence.create(name: "Bison", category_id: 20)
Correspondence.create(name: "Chipmunk", category_id: 20)
Correspondence.create(name: "Goat", category_id: 20)
Correspondence.create(name: "Cattle", category_id: 20)
Correspondence.create(name: "Horse", category_id: 20)
Correspondence.create(name: "Pig", category_id: 20)
Correspondence.create(name: "Rabbit", category_id: 20)
Correspondence.create(name: "Reindeer", category_id: 20)
Correspondence.create(name: "Sheep", category_id: 20)
Correspondence.create(name: "Squirrel", category_id: 20)
Correspondence.create(name: "Salmon", category_id: 17)
Correspondence.create(name: "Crane", category_id: 23)
Correspondence.create(name: "Flamingo", category_id: 23)
Correspondence.create(name: "Chicken", category_id: 23)
Correspondence.create(name: "Duck", category_id: 23)
Correspondence.create(name: "Egret", category_id: 23)
Correspondence.create(name: "Heron", category_id: 23)
Correspondence.create(name: "Goose", category_id: 23)
Correspondence.create(name: "Ibis", category_id: 23)
Correspondence.create(name: "Nighthawk", category_id: 23)
Correspondence.create(name: "Kingfisher", category_id: 23)
Correspondence.create(name: "Osprey", category_id: 23)
Correspondence.create(name: "Parrot", category_id: 23)
Correspondence.create(name: "Pelican", category_id: 23)
Correspondence.create(name: "Peacock", category_id: 23)
Correspondence.create(name: "Grasshopper", category_id: 24)
Correspondence.create(name: "Sandpiper", category_id: 23)
Correspondence.create(name: "Seagull", category_id: 23)
Correspondence.create(name: "Moth", category_id: 24)
Correspondence.create(name: "Turkey", category_id: 23)
Correspondence.create(name: " Bee", category_id: 24)
Correspondence.create(name: "Turtle", category_id: 22)
Correspondence.create(name: "Frog", category_id: 22)
Correspondence.create(name: "Crocodile", category_id: 22)
Correspondence.create(name: "Air", category_id: 9)
Correspondence.create(name: "Black", category_id: 11)
Correspondence.create(name: "Pink", category_id: 11)
Correspondence.create(name: "Angelica", category_id: 15)
Correspondence.create(name: "Iris", category_id: 15)
Correspondence.create(name: "Clover", category_id: 15)
Correspondence.create(name: "Catnip", category_id: 15)
Correspondence.create(name: "Cypress", category_id: 14)
Correspondence.create(name: "Mustard", category_id: 13)
Correspondence.create(name: "Angelite", category_id: 16)
Correspondence.create(name: "Larimar", category_id: 16)
Correspondence.create(name: "Aragonite", category_id: 16)
Correspondence.create(name: "Beryl", category_id: 16)
Correspondence.create(name: "Ruby", category_id: 16)
Correspondence.create(name: "Rose Quartz", category_id: 16)
Correspondence.create(name: "Nanna", category_id: 18)
Correspondence.create(name: "Macha", category_id: 18)
Correspondence.create(name: "Nemesis", category_id: 18)
Correspondence.create(name: "Persephone", category_id: 18)
Correspondence.create(name: "Loki", category_id: 19)
Correspondence.create(name: "Pluto", category_id: 19)
Correspondence.create(name: " Coyote ", category_id: 20)
Correspondence.create(name: "Wolf ", category_id: 20)
Correspondence.create(name: "Capricorn", category_id: 1)
Correspondence.create(name: "Sunday", category_id: 6)
Correspondence.create(name: "Lughnasadh", category_id: 29)
Correspondence.create(name: "Mabon", category_id: 29)
Correspondence.create(name: "Jera", category_id: 8)
Correspondence.create(name: "Northwest", category_id: 10)
Correspondence.create(name: "Purple", category_id: 11)
Correspondence.create(name: "1", category_id: 28)
Correspondence.create(name: "7", category_id: 28)
Correspondence.create(name: "9", category_id: 28)
Correspondence.create(name: "4", category_id: 28)
Correspondence.create(name: "10", category_id: 28)
Correspondence.create(name: "Sun", category_id: 27)
Correspondence.create(name: "World", category_id: 27)
Correspondence.create(name: "Cherry", category_id: 14)
Correspondence.create(name: "Spindletree", category_id: 14)
Correspondence.create(name: "Moonstone", category_id: 16)
Correspondence.create(name: "Justitia", category_id: 18)
Correspondence.create(name: "Dionysus", category_id: 19)
Correspondence.create(name: "Janus", category_id: 19)
Correspondence.create(name: "Vishnu", category_id: 19)
Correspondence.create(name: "Brownies", category_id: 25)
Correspondence.create(name: "Gazelle", category_id: 20)
Correspondence.create(name: "Moose", category_id: 20)
Correspondence.create(name: "Bluebird", category_id: 23)
Correspondence.create(name: "Firefly", category_id: 24)
Correspondence.create(name: "Moon", category_id: 2)
Correspondence.create(name: " Mars", category_id: 2)
Correspondence.create(name: "Sun", category_id: 2)
Correspondence.create(name: "Aries", category_id: 1)
Correspondence.create(name: "Leo", category_id: 1)
Correspondence.create(name: "Tuesday", category_id: 6)
Correspondence.create(name: "Fire", category_id: 9)
Correspondence.create(name: "5", category_id: 28)
Correspondence.create(name: "13", category_id: 28)
Correspondence.create(name: "3", category_id: 28)
Correspondence.create(name: " 1", category_id: 28)
Correspondence.create(name: "Red", category_id: 11)
Correspondence.create(name: "Yellow", category_id: 11)
Correspondence.create(name: "Strength", category_id: 27)
Correspondence.create(name: "Temperance", category_id: 27)
Correspondence.create(name: "Wands", category_id: 27)
Correspondence.create(name: "Juniper", category_id: 14)
Correspondence.create(name: "Apple", category_id: 14)
Correspondence.create(name: "Peppermint", category_id: 15)
Correspondence.create(name: "Gardenia", category_id: 15)
Correspondence.create(name: "Geranium", category_id: 15)
Correspondence.create(name: "Broom", category_id: 15)
Correspondence.create(name: " Cinnamon", category_id: 13)
Correspondence.create(name: "Grain (corn)", category_id: 13)
Correspondence.create(name: "Reed", category_id: 13)
Correspondence.create(name: "Thistle", category_id: 13)
Correspondence.create(name: "Zoisite", category_id: 16)
Correspondence.create(name: "Jasper", category_id: 16)
Correspondence.create(name: "Sunstone", category_id: 16)
Correspondence.create(name: "Tanzanite", category_id: 16)
Correspondence.create(name: "Kali", category_id: 18)
Correspondence.create(name: "Ishtar", category_id: 18)
Correspondence.create(name: "Anat", category_id: 18)
Correspondence.create(name: "The Morrigan", category_id: 18)
Correspondence.create(name: "Minerva", category_id: 18)
Correspondence.create(name: "Sekhmet", category_id: 18)
Correspondence.create(name: "Surya", category_id: 19)
Correspondence.create(name: "Mars", category_id: 19)
Correspondence.create(name: "Ares", category_id: 19)
Correspondence.create(name: "Poseidon", category_id: 19)
Correspondence.create(name: "Salamanders", category_id: 25)
Correspondence.create(name: "Sylphs", category_id: 25)
Correspondence.create(name: "Antelope", category_id: 20)
Correspondence.create(name: "Beaver", category_id: 20)
Correspondence.create(name: "Badger", category_id: 20)
Correspondence.create(name: "Hippopotamus", category_id: 20)
Correspondence.create(name: "Caribou", category_id: 20)
Correspondence.create(name: "Wolf", category_id: 20)
Correspondence.create(name: "Tiger", category_id: 20)
Correspondence.create(name: "Cobra", category_id: 22)
Correspondence.create(name: "Condor", category_id: 23)
Correspondence.create(name: "Chickadee", category_id: 23)
Correspondence.create(name: "Ant", category_id: 24)